### ISSUE TITLE
O365 Handle checkpoints > 23 hours in the past

### ISSUE THREAD

**Issue by waab76** [Graylog2/graylog-plugin-integrations#522]
As a Graylog User, I want the O365 Input to pull data correctly even if it has not pulled data in quite some time.

# Notes:
Microsoft has rather strict time constraints on the O365 Management API.  You cannot pull data for start time > 7 days ago and you cannot pull data if start time is 24 hours or more before end time.  For a variety of reasons, we could get into a situation where the existing checkpoint for the input is > 24 hours before the current time or >  days in the past.  We should build a "catch up" mechanism into the Input to handle these situations without failing.

# Open Questions (probably need Nick to answer)
- [ ] Is it OK for "catch up" logic to run over multiple executions rather than catching up on a single execution?

# Input Criteria
- [ ] Input functions with basic checkpointing

# Tasks
- [ ] Determine "catch up" logic and document on project Confluence page
- [ ] Implement "catch up" logic
- [ ] Add JUnit tests for "catch up" logic
- [ ] Manually verify "catch up" logic

# Acceptance Criteria
- [ ] If checkpoint time for a data type is > 24 hours in the past, Input will catch up without violating Microsoft's query time range constraints
- [ ] If checkpoint time for a data type is > 7 days in the past, Input will retrieve data for last 7 days
