### ISSUE TITLE
Update Palo Alto Codec

### ISSUE THREAD

**Issue by waab76** [Graylog2/graylog-plugin-integrations#540]
As a Graylog customer, I want Graylog to handle both Palo Alto 9.1.2 and earlier versions of GlobalProtect logs and also 9.1.3 and later versions.

# Notes
* 9.0 - 9.1.2 GlobalProtect log format: https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/globalprotect-log-fields/globalprotect-log-fields-for-panos-910-through-912.html#id1ef9df3b-3c28-4739-a4ac-b15bea790a98
* 9.1.3+ GlobalProtect log format: https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/globalprotect-log-fields/globalprotect-log-fields-for-panos-910-through-912.html#id1ef9df3b-3c28-4739-a4ac-b15bea790a98

# Input Criteria
- [x] Palo Alto 9.x Input works
- [x] Palo Alto 9.1.3 Global Protect log format known
- [x] Data mappings for new field(s) in 9.1.3

# Tasks
- [x] Create new template for 9.1.3+ GlobalProtect logs
- [x] Update Codec to recognize both <= 9.1.2 and >= 9.1.3 formats and choose correct template
- [x] Add JUnits for differentiating <= 9.1.2 and >= 9.1.3 logs
- [x] Backport fix to 3.3 branch

# Acceptance Criteria
- [x] Palo Alto 9.x Input successfully parses Global Protect logs for version 9.1.2 and earlier
- [x] Palo Alto 9.x Input successfully parses Global Protect logs for version 9.1.3 and later
- [ ] Changes backported to 3.3 branch
