### ISSUE TITLE
Slack Plugin should support Backlog Message Limit

### ISSUE THREAD

**Issue by lingpri** [Graylog2/graylog-plugin-integrations#623]
Slack Notification users may want to limit the number of backlog messages sent in a Slack notification in order to prevent flooding their channels with data.  To support this, we will add a config option to Slack Notification to set a backlog message limit.  When set, this should ensure that no more than the specified number of backlog messages are sent to Slack.

As an example, a user could set their Alert to include 50 Backlog Messages but they may only want 3 messages to be included in the Slack Notification.

# Input Criteria
- [x] Slack plugin works

# Output Criteria
- [x] Slack Notification has configuration options to allow users to set a Backlog Message Limit
- [x] Text on the UI makes it clear that the Slack Notification setting will override Alert settings
- [x] When no Backlog Message Limit is set, Slack Notifications send all included Backlog Messages to Slack
- [x] When the Backlog Message Limit is set, Slack Notifications do not send more than the specified number of Backlog Messages to Slack
- [x] Slack Notifications default to limit 0 in backend and frontend
- [x] Users are able to disable the limit after it has been enabled

# Tasks
- [x] Determine the best way to represent the limit in code
- [x] Update config classes to store all data related to the limit
- [x] Update UI to enable users to enter limit
- [x] Update Slack logic to enforce the limit
- [x] JUnit tests written to validate that the limit is enforced
- [x] Test locally
- [x] Slack Notification documentation updated to describe the additional Message Backlog Limit

# Improvements
- [x] Fix help block for custom message and error message description (https://github.com/Graylog2/graylog-plugin-integrations/pull/639/commits/5405878fa0409d8ee50ade8ac3a4e74453c7ade1)

# Reference
- [ ] https://github.com/graylog-labs/graylog-plugin-slack/tree/master/src/main

**Comment by lingpri** [comment]
![backlog_items](https://user-images.githubusercontent.com/6947168/98615826-1b7ad780-22c1-11eb-869f-ea0b2daf8091.png)
