### ISSUE TITLE
Palo Alto 10 Schema Updates

### ISSUE THREAD

**Issue by waab76** [Graylog2/graylog-plugin-integrations#637]
As a Graylog customer, I want the Palo Alto input to support PAN-OS 10 schema changes.

# Notes
Palo Alto 10 schema changes in the spreadsheet provided by Nick

# Input Criteria
- [x] Palo Alto 9.x input works

# Output Criteria
- [x] Palo Alto 9.x Input renamed to Palo Alto 9+
- [x] Palo Alto Threat schema updated
- [x] Palo Alto Traffic schema updated
- [x] Palo Alto System schema updated
- [x] Palo Alto Correlation schema updated
- [x] Palo Alto HIP schema updated
- [x] Palo Alto Global Protect 9.1.3+ schema updated
- [x] JUnit tests updated
- [x] All changes backported to 4.0
- [x] Schema changes backported to 3.3

# Tasks
- [x] Update the input name
- [x] Update Threat schema
- [x] Update Threat JUnit
- [x] Update Traffic schema
- [x] Update Traffic JUnit
- [x] Update System schema
- [x] Update System JUnit
- [x] Update Correlation schema
- [x] Update Correlation JUnit
- [x] Update HIP schema
- [x] Update HIP JUnit
- [x] Update Global Protect 9.1.3+
- [x] Update Global Protect JUnit
- [x] Backport schema and Input to 4.0
- [x] Backport schema onlyto 3.3
