### ISSUE TITLE
Clean up integrations guice config for Forwarder

### ISSUE THREAD

**Issue by waab76** [Graylog2/graylog-plugin-integrations#675]
Enterprise Integrations has separate Guice configurations for Forwarder and non-Forwarder use cases.  In the 4.0 release, some new Integrations plugins do not work in the Forwarder and thus we need a similar Guice split in Integrations.  We should also double-check components in Enterprise Integrations.

# Input Conditions
- None

# Acceptance Criteria
- [ ] Cloud Forwarder is able to start with 4.0 codebase

# Tasks
- [ ] Set up forwarder/server split in Integrations Guice module
- [ ] Move all Notifications (Integrations and Enterprise) to the server configuration
- [ ] Move all Outputs to the server configuration
- [ ] Move any Mongo-dependent Inputs to the server configuration
- [ ] Keep all non-Mongo-dependent Inputs in the Forwarder configuration

**Comment by juju2112** [comment]
I'm still seeing Guice errors when I try to run the forwarder with the integrations plugin. 

I followed the instructions here to install the forwarder on a clean VM:

https://github.com/Graylog2/graylog-plugin-cloud/wiki/Forwarder#forwarder-operating-system-packages

Below are the logs from trying to start the service. Ignore the parts at the beginning here I didn't have Java installed yet.

[service.log](https://github.com/Graylog2/graylog-plugin-integrations/files/5765352/service.log)
[forwarder.log](https://github.com/Graylog2/graylog-plugin-integrations/files/5765353/forwarder.log)

If I remove the integrations plugin from the plugins folder, it starts just fine.

This is from a build this morning:

https://jenkins.ci.torch.sh/job/Release-Jobs/job/Graylog-Forwarder-Package-Build/115/console

**Comment by danotorrey** [comment]
@juju2112 I believe the backport of fix should fix this issue https://github.com/Graylog2/graylog-plugin-integrations/pull/693 since it puts the change on the `cloud-4.0` branch. Can you please test once more after it is merged?

**Comment by juju2112** [comment]
@danotorrey Ah! I missed that. Okay, I'll check again once it's merged.

**Comment by juju2112** [comment]
@danotorrey I have the manifest using the `4.0` branch for this. Should I change it to `cloud-4.0`? 

https://github.com/Graylog2/graylog-project-internal/blob/master/manifests/cloud/cloud-forwarder.json#L22-L23

**Comment by danotorrey** [comment]
> @danotorrey I have the manifest using the `4.0` branch for this. Should I change it to `cloud-4.0`?

@juju2112 Yes, that should resolve it. `cloud-4.0` should be used for both `graylog-plugin-integrations` and `graylog-plugin-enterprise-integrations`

Whenever the core devs create a new `cloud-4.0` branch, we'll need to remember to update this manifest too. 

Question: Should the manifest also have the `-4.0` extension in the file name like the existing [cloud-4.0.json](https://github.com/Graylog2/graylog-project-internal/blob/master/manifests/cloud/cloud-4.0.json) manifest?

**Comment by juju2112** [comment]
Yeah, I can update that.

**Comment by juju2112** [comment]
I cut a new release of the forwarder for the 4.0 branch, tested it on a fresh VM, and it starts up just fine.

**Comment by juju2112** [comment]
@danotorrey I also updated the graylog-forwarder docker image.

**Comment by danotorrey** [comment]
Great news. Thanks @juju2112
