### ISSUE TITLE
Grey Noise basic lookup data adapter

### ISSUE THREAD

**Issue by waab76** [Graylog2/graylog-plugin-integrations#694]
As a Graylog user, I want a Grey Noise data adapter that will allow me to filter known noisy IPs in order to better focus on real threats.

# Notes
Information on GreyNoise and a technical contact can be found in Nick's Threat Intel doc.

# Open Questions
- [ ] Should we require users to provide their own API keys for this data adapter or should we talk to Grey Noise about using a general Graylog API key?
- [ ] Look at implementing a local cache

# Input Criteria
- [x] Basic requirements are described in Threat Intel doc

# Acceptance Criteria
- [ ] Basic Grey Noise adapter available in Graylog Open Source
- [ ] Grey Noise adapter has a local cache
- [ ] Grey Noise adapter covered in Graylog documentation
- [ ] JUnit tests for all new/modified code
- [ ] Backport for next release

# Tasks
- [ ] Create a reusable GreyNoise REST client capable of querying IP Quick Check API
- [ ] Create a Grey Noise quick check data adapter
- [ ] Write JUnit tests
- [ ] TBD

**Comment by danotorrey** [comment]
Closed by #760.
