### ISSUE TITLE
Alarm Callback to Notification Migration

### ISSUE THREAD

**Issue by waab76** [Graylog2/graylog-plugin-integrations#724]
As a Graylog customer with a large number of Alarm Callbacks configured, I need a mechanism to migrate my existing Alarm Callbacks to Notifications.

# Notes
This comes from ticket 4597 where a customer has "hundreds" of HTTP Alarm Callbacks configured.  For HTTP Alarm Callbacks/Notifications, the only configurable piece is the HTTP endpoint and thus migration should be pretty straightforward.  However, customers need to be aware that the payload has changed between Alarm Callbacks and Notifications and ensure that their HTTP endpoint can handle the new payload.

# Acceptance Criteria
- [x] Automated mechanism exists for customers to migrate HTTP Alarm Callbacks to HTTP Notifications
- [x] Mechanism allows customers to specify new HTTP endpoint
- [x] Migration does not break links with existing Events

# Tasks
- [ ] TBD

**Comment by waab76** [comment]
Added script to new repo in Graylog-Labs
